version: "3.8"

services:
  db:
    image: mysql:oraclelinux8
    build: .
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASS}
    ports:
      - "3306:3306"
    expose:
      - "3306"
    volumes:
      - data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$$MYSQL_ROOT_PASSWORD"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - mysql_net

  django_gunicorn:
    volumes:
      - static:/static
    env_file:
      - /home/ynot/fitweb/whatzthefit/.env
    build:
      context: .
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    links:
      - db
    restart: always
    networks:
      - mysql_net 

  nginx:
    build: ./nginx
    volumes:
      - static:/static
      - media:/media
    ports:
      - "84:84"
    depends_on:
      - django_gunicorn
    networks:
      - mysql_net

  

 

volumes:
  data:
  static:
  media:

networks:
  - mysql_net