version: "3.7"

services:
  django_gunicorn:
    volumes:
      - static:/static
    env_file:
      - /home/ynot/fitweb/whatzthefit/.env
    build:
      context: .
    ports:
      - "8080:8080"
    # depends_on:
    #   - nginx

  nginx:
    build: ./nginx
    volumes:
      - static:/static
    ports:
      - "84:84"
    depends_on:
      - django_gunicorn

volumes:
  static:
