version: "3.7"

services:
  django_gunicorn:
    volumes:
      - static:/static
    env_file:
      - /home/ynot/fitweb/whatzthefit/.env
    build:
      context: .
    ports:
      - "8080:8080"

  nginx:
    build: ./nginx
    volumes:
      - static:/static
      - media:/media
    ports:
      - "84:84"
    depends_on:
      - django_gunicorn
  
  db:
    image: mysql:oraclelinux8
    container_name: fitweb_mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
    ports:
      - "3306:3306"
    expose:
      - "3306"
    volumes:
      - data:/var/lib/mysql
 

volumes:
  static:
  data:
  media:
