version: "3.7"

services:
  db:
    build: .
    image: mysql:oraclelinux8
    container_name: fitweb_mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'password'
      MYSQL_DATABASE: 'whatzthefit'
      MYSQL_USER: 'root'
      MYSQL_PASSWORD: 'password'
    ports:
      - "3306:3306"
    expose:
      - "3306"
    volumes:
      - data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "${DB_USER}", "-p${MYSQL_ROOT_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 3

  django_gunicorn:
    volumes:
      - static:/static
    env_file:
      - /home/ynot/fitweb/whatzthefit/.env
    build:
      context: .
    ports:
      - "8080:8080"
    depends_on:
      - db


  nginx:
    build: ./nginx
    volumes:
      - static:/static
      - media:/media
    env_file:
      - .env
    ports:
      - "84:84"
    depends_on:
      - django_gunicorn
  

volumes:
  static:
  data:
  media:

