# Generated by Django 4.2.7 on 2024-02-10 15:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('msg_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('New', 'New message'), ('Seen', 'Read and no action required'), ('Todo', 'Actions are to be performed'), ('Res', 'issues resolved')], default='New', max_length=4)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_message', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Messages',
                'ordering': ('msg_date', 'user'),
            },
        ),
    ]
