# Generated by Django 4.2.7 on 2024-01-01 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='status',
            field=models.CharField(choices=[('New', 'New message'), ('Seen', 'Read and no action required'), ('Todo', 'Actions are to be performed'), ('Res', 'issues resolved')], default='New', max_length=4),
        ),
    ]
